# Header
menu:
  About: '#about'
  Projects: '#portfolio'
  Skills: '#skills'
  Contact: '#contact'
rss: /atom.xml

profilePic: 'img/profile.jpg'
emailAddress: 'sumen.tse@gmail.com'

skills:
  - HTML5
  - Bootstrap
  - CSS3
  - SASS
  - Javascript
  - Jquery
  - AngularJS
  - React
  - NodeJS
  - PHP
  - Python
  - MySQL
  - MongoDB
  - GIT
  - Gulp
  - WordPress
  - Linux
  - Photoshop
  - Illustrator

# Miscellaneous
google_analytics: UA-96086695-1
github: https://github.com/sumentse